<GuessWordGame>:
    button: play_button
    Label:
        font_size: 50
        center_x: self.parent.width / 2
        top: self.parent.top - self.parent.height / 10
        text: "Welcome to Guess Word Game"

    Button:
        id: play_button
        center_x: self.parent.width / 2
        top: self.parent.top - 4 * self.parent.height / 10
        text: "Play"
        font_size: 70
        on_release: root.test()
    