<DoodleWordMenu>:
    BoxLayout:
        orientation: 'vertical'
        padding: [200, 100]
        spacing: 30
        Label:
            text: "Doodle Word"
            font_size: 40
        Button:
            text: "Почати гру"
            font_size: 40
            on_press: root.manager.current = 'game'
        Button:
            text: 'Вийти з гри'
            font_size: 40
            on_press: app.stop()